import { Hostage } from './app.interfaces';

export const hostages: Partial<Hostage>[] = [
  {
    name: 'ליאת אצילי',
    englishName: 'Liat Atzili',
    age: '49',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hwkpollk/ליאת-אצילי.jpg',
  },
  {
    name: 'אביב אצילי',
    englishName: 'Aviv Atzili',
    age: '49',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/oivl5pdf/אביב-אצילי.jpg',
  },
  {
    name: 'איתן מור',
    englishName: 'Eitan Mor',
    age: '23',
    address: ' ירושלים',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/spnagum2/איתן-מור.jpg',
  },
  {
    name: 'ג׳ודי ויינשטיין',
    englishName: 'Judy Weinstein',
    age: '70',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/pz5jny0l/ג-ודי-ויינשטיין.jpg',
  },
  {
    name: 'איתן לוי',
    englishName: 'Eitan Levi',
    address: ' בת ים',
    tag: 'נחטף בדרכו לקיבוץ בארי',
    age: '53',
    img: 'https://cfcdn.kan.org.il/media/qt5dzlu0/איתן-לוי.jpg',
  },
  {
    name: 'יוסף אלזיאדנה',
    englishName: 'Yosef Alziyadneh',
    age: '53',
    address: ' רהט',
    tag: 'נחטף מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/zqzlterr/יוסף-אלזיאדנה.jpg',
  },
  {
    name: 'מישל ניסנבאום',
    englishName: 'Michel Nisenbaum',
    age: '59',
    address: ' שדרות',
    tag: 'נחטף מאזור רעים',
    img: 'https://cfcdn.kan.org.il/media/dh1jkpip/מישל-ניסנבאום.jpg',
  },
  {
    name: 'מתן צנגאוקר',
    englishName: 'Matan Zangauker',
    age: '23',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/01fbqmzn/מתן-צנגאוקר.jpg',
  },
  {
    name: 'עמית סוסנה',
    englishName: 'Amit Soussana',
    age: '40',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/3cdiimun/עמית-סוסנה.jpg',
  },
  {
    name: 'גלי טרשנסקי',
    englishName: 'Gali Tarshansky',
    age: '13',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/5gype5fz/גלי-טרשנסקי.jpg',
  },
  {
    name: 'עדה שגיא',
    englishName: 'Ada Sagi',
    age: '75',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/k1bnhz4a/עדה-שגיא.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599452/',
  },
  {
    name: 'יונתן סמרנו',
    englishName: 'Yonathan Samerano',
    age: '21',
    address: ' תל אביב',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/iigne2zd/יונתן-סמרנו.jpg',
  },
  {
    name: 'אופליה רויטמן',
    englishName: 'Ofelia Roitman',
    age: '77',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/vocggjkp/אופליה-רויטמן.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/573750/',
  },
  {
    name: 'הילה רותם',
    englishName: 'Hila Rotem',
    age: '13',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/unmfwmki/הילה-שושני-רותם.jpg',
  },
  {
    name: 'רעיה רותם',
    englishName: 'Raaya Rotem',
    age: '54',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/ir3fj2ag/רעיה-רותם.jpg',
  },
  {
    name: 'ליאם אור',
    englishName: 'Liam Or',
    age: '18',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/0ybp3y2v/אור-ליאם.jpg',
  },
  {
    name: 'אליקים ליבמן',
    englishName: 'Elyakim Libman',
    age: '24',
    address: ' קרית ארבע',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/2dvbhl34/אליקים-ליבמן.jpg',
  },
  {
    name: 'אנדריי קוזלוב',
    englishName: 'Andrey Kozlov',
    age: '27',
    address: ' ראשון לציון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/5jxpte2f/אנדריי-קוזלוב.jpg',
  },
  {
    name: 'שני גורן',
    englishName: 'Shani Goren',
    age: '29',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/jsjdkpvo/שני-גורן.jpg',
  },
  {
    name: 'גדי חגי',
    englishName: 'Gadi Haggai',
    age: '73 ',
    address: 'ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/gcmbegle/גדי-חגי.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599442/',
  },
  {
    name: 'עלמה אור',
    englishName: 'Alma Or',
    age: '13',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/5dmbmgi4/עלמה-אור.jpg',
  },
  {
    name: 'נועם אור',
    englishName: 'Noam Or',
    age: '17',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/bzsooeyf/נועם-אור.jpg',
  },
  {
    name: 'דרור אור',
    englishName: 'Dror Or',
    age: '46',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/fcgpxrod/דרור-אור.jpg',
  },
  {
    name: 'נוגה וייס',
    englishName: 'Noga Weiss',
    age: '18',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/0xunook4/נוגה-וייס.jpg',
  },
  {
    name: 'שירי וייס',
    englishName: 'Shiri Weiss',
    age: '53',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/vqqfogw2/שירי-וייס.jpg',
  },
  {
    name: 'שגיא דקל חן',
    englishName: 'Sagi Dekel Chen',
    age: '35',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/uz1arkmf/שגיא-דקל-חן.jpg',
  },
  {
    name: 'אמילי הנד',
    englishName: 'Emily Hand',
    age: '8',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/qcse1vid/אמילי-הנד.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/598473/',
  },
  {
    name: 'עדן ירושלמי',
    englishName: 'Eden Yerushalmi',
    age: '24',
    address: ' תל אביב',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/xefo1ak5/עדן-ירושלמי.jpg',
  },
  {
    name: "נורלין אגוג'ו",
    englishName: 'Noralin Agojo',
    age: '60',
    address: ' הפיליפינים',
    tag: 'נחטפה מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/owxcklr1/נורלין-אגוגו.jpg',
  },
  {
    name: "ביפין ג'ושי",
    englishName: 'Bipin Joshi',
    age: '23',
    address: ' נפאל',
    tag: 'נחטף מקיבוץ עלומים',
    img: 'https://cfcdn.kan.org.il/media/u53alnk0/ביפין-גושי.jpg',
  },
  {
    name: 'איציק אלגרט',
    englishName: 'Itzhak Elgaret',
    age: '69',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/xlqpur2m/איציק-אלגרט.jpg',
  },
  {
    name: 'שלומי זיו',
    englishName: 'Shlomi Ziv',
    age: '39',
    address: ' אלקוש',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/d5abpgv1/שלומי-זיו.jpg',
  },
  {
    name: 'נדב פופלוול',
    englishName: 'Nadav Popplewell',
    age: '51',
    address: ' נירים',
    tag: 'נחטף מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/dvblkbuc/נדב-פופלוול.jpg',
  },
  {
    name: 'חנה פרי',
    englishName: 'Hanna Peri',
    age: '79',
    address: ' נירים',
    tag: 'נחטפה מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/4kooz5ip/חנה-פרי.jpg',
  },
  {
    name: 'חיים פרי',
    englishName: 'Chaim Peri',
    age: '79',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/is5nyb2h/חיים-פרי.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573764/',
  },
  {
    name: 'עידן אלכסנדר',
    englishName: 'Idan Alexander',
    age: '19',
    address: ' ארה"ב',
    tag: 'נחטף מהבסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/fc1grglo/עידן-אלכסנדר.jpg',
  },
  {
    name: 'אופיר צרפתי',
    englishName: 'Ofir Tzarfati',
    age: '27',
    address: ' קרית ביאליק',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/0tnhov4k/אופיר-צרפתי.jpg',
  },
  {
    name: 'עפרה קידר',
    englishName: 'Ofra Keidar',
    age: '70',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/5rvieykk/עפרה-קידר.jpg',
  },
  {
    name: 'אוריון הרננדס ראדו',
    englishName: 'Oryon Hernandez',
    age: '30',
    address: ' מקסיקו',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/aauhtew2/אוריון-הרננדס.jpg',
  },
  {
    name: 'אריה זלמנוביץ',
    englishName: 'Arieh Zalmanovich',
    age: '85',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/vwhotqkm/אריה-זלמנוביץ.jpg',
  },
  {
    name: 'אור יעקב',
    englishName: 'Or Yaakov',
    age: '16',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/5jefyjro/אור-יעקב.jpg',
  },
  {
    name: 'יגיל יעקב',
    englishName: 'Yagil Yaakov',
    age: '13',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/jykb2tpx/יגיל-יעקב.jpg',
  },
  {
    name: 'גיא אילוז',
    englishName: 'Guy Illouz',
    age: '26',
    address: ' תל אביב',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/oxbhpruf/גיא-אילוז.jpg',
  },
  {
    name: 'מרגלית מוזס',
    englishName: 'Margalit Mozes',
    age: '77',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/lg3lt4ah/מרגלית-מוזס.jpg',
  },
  {
    name: 'איתי סבירסקי',
    englishName: 'Itai Svirsky',
    age: '38',
    address: ' תל אביב',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/0paovuhb/איתי-סבירסקי.jpg',
  },
  {
    name: 'אלמוג סרוסי',
    englishName: 'Almog Sarusi',
    age: '25',
    address: ' רעננה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/xugc5p2z/אלמוג-סרוסי.jpg',
  },
  {
    name: 'עאישה אלזיאדנה',
    englishName: 'Aisha Alziyadneh',
    age: '17',
    address: ' רהט',
    tag: 'נחטפה מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/2xolx4gm/299x231.jpg',
  },
  {
    name: 'עדן זכריה',
    englishName: 'Eden Zecharya',
    age: '28',
    address: ' קרית שמונה',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/wqybklzr/עדן-זכריה.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/575191/',
  },
  {
    name: 'עמירם קופר',
    englishName: 'Amiram Cooper',
    age: '84',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/tzuhhtle/עמירם-קופר.jpg',
  },
  {
    name: 'נועם אביגדורי',
    englishName: 'Noam Avigdori',
    age: '12',
    address: ' הוד השרון',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/pfjfhkmh/נועם-אביגדורי.jpg',
    link: 'https://kan.org.il/content/kan/kan-11/p-578726/589189/',
  },
  {
    name: 'יאיר הורן',
    englishName: 'Yair Horn',
    age: '45',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ro5k3r50/יאיר-הורן.jpg',
  },
  {
    name: 'איתן הורן',
    englishName: 'Eitan Horn',
    age: '37',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/3iphiwvj/איתן-הורן.jpg',
  },
  {
    name: 'ליאור רודאיף',
    englishName: 'Lior Rudaeff',
    age: '61',
    address: ' ניר יצחק',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/vctlnodp/398063883_10161431415177088_3568294037318690713_n.jpg',
  },
  {
    name: 'שרון אביגדורי',
    englishName: 'Sharon Avigdori',
    age: '52',
    address: ' הוד השרון',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/pjqpsmul/שרון-אביגדורי.jpg',
    link: 'https://kan.org.il/content/kan/kan-11/p-578726/589189/',
  },
  {
    name: 'זיו ברמן',
    englishName: 'Ziv Berman',
    age: '26',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/z1jna5gf/זיו-ברמן.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599405/',
  },
  {
    name: 'גלי ברמן',
    englishName: 'Gali Berman',
    age: '26',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/l2jnxztx/גלי-ברמן.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599405/',
  },
  {
    name: 'אירנה טטי',
    englishName: 'Irena Tati',
    age: '73',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/bceftxuw/אירנה-טטי.jpg',
  },
  {
    name: 'ספיר כהן',
    englishName: 'Sapir Cohen',
    age: '29',
    address: ' קרית אתא',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/mlfb5wvx/ספיר-כהן.jpg',
  },
  {
    name: 'סשה אלכסנדר טרופנוב',
    englishName: 'Sasha Alexander Trupanob',
    age: '28',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/sxdpahk0/סשה-טרופנוב.jpg',
  },
  {
    name: 'עמית שני',
    englishName: 'Amit Shani',
    age: '16',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/gcjpv1dv/עמית-שני.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599527/',
  },
  {
    name: 'יוסף חיים אוחנה',
    englishName: 'Yosef Chaim Ohana',
    age: '23',
    address: ' קרית מלאכי',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/3etpew2g/יוסף-חיים-אוחנה.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599353/',
  },
  {
    name: 'יותם חיים',
    englishName: 'Yotam Haim',
    age: '28',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/4sop24pr/יותם-חיים.jpg',
  },
  {
    name: 'טל חיימי',
    englishName: 'Tal Chaimi',
    age: '42',
    address: ' ניר יצחק',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/dihhcxth/טל-חיימי.jpg',
  },
  {
    name: 'ירדן ביבס',
    englishName: 'Yarden Bibas',
    age: '34',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/thincxoa/ירדן-ביבס.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599517/',
  },
  {
    name: 'חנה קציר',
    englishName: 'Hanna Katzir',
    age: '77',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/2xnhrkwb/חנה-קציר.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599525/',
  },
  {
    name: 'שגב כלפון',
    englishName: 'Segev Kalfon',
    age: '26',
    address: ' דימונה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/lvujl0no/שגב-כלפון.jpg',
  },
  {
    name: 'תמיר אדר',
    englishName: 'Tamir Adar',
    age: '38',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/gh0pnm43/תמיר-אדר.jpg',
  },
  {
    name: 'תמיר נמרודי',
    englishName: 'Tamir Nimrod',
    age: '18',
    address: ' נירית',
    tag: 'נחטף מהבסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/l5pjgixc/תמיר-נמרודי.png',
    link: 'https://www.kan.org.il/content/kan/kan-11/p-12043/s7/590317/',
  },
  {
    name: 'נילי מרגלית',
    englishName: 'Nili Margalit',
    age: '41',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/q3cgmehm/נילי-מרגלית.jpg',
  },
  {
    name: 'יגב בוכשטב',
    englishName: 'Yagev Buchshtab',
    age: '34',
    address: ' נירים',
    tag: 'נחטף מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/1xwj2lci/יגב-בוכשטב.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599356/',
  },
  {
    name: 'רימון קירשט',
    englishName: 'Rimon Kirsht',
    age: '36',
    address: ' נירים',
    tag: 'נחטפה מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/g5jjup1p/רימון-קירשט.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/590370/',
  },
  {
    name: 'ילנה טרופנוב',
    englishName: 'Yelena Trupanob',
    age: '50',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/n51jz3un/ילנה-טרופנוב.jpg',
    link: 'https://www.kan.org.il/content/kan-news/defense/588988/',
  },
  {
    name: 'רביד כץ',
    englishName: 'Ravid Katz',
    age: '51',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/rjgajtbw/רביד-כץ.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
  },
  {
    name: 'דורון שטיינברכר',
    englishName: 'Doron Steinbrecher',
    age: '30',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/us2oiep1/דורון-שטיינברכר.jpg',
  },
  {
    name: 'שלמה מנסור',
    englishName: 'Shlomo Mansour',
    age: '85',
    address: ' כיסופים',
    tag: 'נחטף מקיבוץ כיסופים',
    img: 'https://cfcdn.kan.org.il/media/550buqht/שלמה-מנסור.jpg',
  },
  {
    name: 'מיה גורן',
    age: '56 ',
    address: 'ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/u5bdgebv/מיה.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599485/',
    englishName: 'Maya Goren',
  },
  {
    name: 'חמזה אלזיאדנה',
    age: '22',
    address: ' רהט',
    tag: 'נחטף מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/uolppudl/חמזה-זיידנה.jpg',
    englishName: 'Hamza Alziyadneh',
  },
  {
    name: 'פרחאן אלקאדי',
    age: '53',
    address: ' דרומית לרהט',
    tag: 'נחטף מקיבוץ מגן',
    img: 'https://cfcdn.kan.org.il/media/btxjdueu/פרחאן-אלקאדי.jpg',
    englishName: 'Farhan Alkadi',
  },
  {
    name: 'בלאל אלזיאדנה',
    age: '19',
    address: ' רהט',
    tag: 'נחטף מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/t5rbdhd4/בלאל-זיידנה.jpg',
    englishName: 'Bilal Alziyadneh',
  },
  {
    name: 'סאמר פואד אל-טלאלקה',
    age: '24',
    address: ' חורה',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/2ylncrow/סאמר-פואד-אל-טלאלקה.jpg',
    englishName: 'Samer Fouad Al-Talalqa',
  },
  {
    name: 'קלמנס מטנגה',
    age: '22',
    address: ' אזרח טנזניה',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/1rseqjdk/קלמנס-מטנגה.jpg',
    englishName: 'Clemance Mtengwa',
  },
  {
    name: "ג'ושוע לואיטו מולל",
    age: '21',
    address: ' אזרח טנזניה',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/2ldfddes/גושוע-לואיטו.jpg',
    englishName: 'Joshua Loitu Mollel',
  },
  {
    name: 'ירדן רומן',
    age: '36',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/g1gaujvo/ירדן-רומן.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573761/',
    englishName: 'Yarden Roman',
  },
  {
    name: 'דולב יהוד',
    age: '35',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/zrvfaqdk/דולב-יהוד.jpg',
    englishName: 'Dolev Yehuda',
  },
  {
    name: 'ארבל יהוד',
    age: '28',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/bgjgwboe/ארבל-יהוד.jpg',
    englishName: 'Arbel Yehuda',
  },
  {
    name: 'טל גולדשטיין',
    age: '9',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/xrzchkek/טל-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
    englishName: 'Tal Goldstein',
  },
  {
    name: 'גל גולדשטיין',
    age: '11',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/dbbfhz4l/גל-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
    englishName: 'Gal Goldstein',
  },
  {
    name: 'אגם גולדשטיין',
    age: '17',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/5mllhmx2/אגם-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
    englishName: 'Agam Goldstein',
  },
  {
    name: 'חן אלמוג גולדשטיין',
    age: '48',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/301fo51f/חן-אלמוג-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
    englishName: 'Chen Almog Goldstein',
  },
  {
    name: 'אלון לולו שמריז',
    age: '26',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/4iupxan1/אלון-לולו-שמריז.jpg',
    englishName: 'Alon Lulu Shamriz',
  },
  {
    name: 'רומי גונן',
    age: '23',
    address: ' כפר ורדים',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/44jkbzmb/רומי-לשם-גונן.jpg',
    link: 'https://www.kan.org.il/content/kan-news/opinions/589039/',
    englishName: 'Romi Gonen',
  },
  {
    name: 'אלכס דנציג',
    age: '75',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hnqicez5/אלכס-דנציג.jpg',
    link: 'https://www.kan.org.il/content/kan/podcasts/p-569737/583124/',
    englishName: 'Alex Dancig',
  },
  {
    name: 'יובל אנגל',
    age: '11',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/uqhfabl4/יובל-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
    englishName: 'Yuval Engel',
  },
  {
    name: 'מיקה אנגל',
    age: '18',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/pbkpcxs5/מיקה-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
    englishName: 'Mika Engel',
  },
  {
    name: 'רונן אנגל',
    age: '55',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/io2ote30/רונן-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
    englishName: 'Ronen Engel',
  },
  {
    name: 'קרינה אנגל-ברט',
    age: '51',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/bwzjzahj/קרינה-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
    englishName: 'Karina Engelbert',
  },
  {
    name: 'יהל שוהם',
    age: '3',
    address: ' מעלה צביה',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/1atcuddn/yahel1.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
    englishName: 'Yahel Shoham',
  },
  {
    name: 'נווה שוהם',
    age: '8',
    address: ' מעלה צביה',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/k0ep5kxj/nave.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
    englishName: 'Nave Shoham',
  },
  {
    name: 'טל שוהם',
    age: '38',
    address: ' מעלה צביה',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/n3wdekrn/tal.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
    englishName: 'Tal Shoham',
  },
  {
    name: 'עדי שוהם',
    age: '38',
    address: ' מעלה צביה',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/kfehmkny/עדי-שוהם-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
    englishName: 'Adi Shoham',
  },
  {
    name: 'עמית בוסקילה',
    age: '28',
    address: ' אשדוד',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/jzpfozkl/amit.jpg',
    englishName: 'Amit Buskila',
  },
  {
    name: 'לואיס נורברטו הר',
    age: '70',
    address: ' אורים',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/ae2b5svh/לואיס-נורברטו-הר.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
    englishName: 'Luis Norberto Haas',
  },
  {
    name: 'ניק בייזר',
    age: '19',
    address: ' באר שבע',
    tag: 'נחטף מהסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/23jbzvlj/nik.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-11/p-12043/s7/590317/',
    englishName: 'Nik Beiser',
  },
  {
    name: 'אלקנה בוחבוט',
    age: '34',
    address: ' מבשרת ציון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/hozf3yhf/אלקנה-בוחבוט-פייסבוק.jpg',
    englishName: 'Elkana Bohbot',
  },
  {
    name: 'אלי שרעבי',
    age: '51',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/ktpjpk0d/אלי-שרעבי-פייסבוק.jpg',
    englishName: 'Eli Sharabi',
  },
  {
    name: 'הירש גולדברג פולין',
    age: '23',
    address: ' ירושלים',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/4kkdceul/הירש-גולדברג-פולין-פייסבוק.jpg',
    englishName: 'Hirsch Goldberg Polin',
  },
  {
    name: 'דניאלה גלבוע',
    age: '19',
    address: ' פתח תקווה',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/tpqhy4kk/דניאלה-גלבוע.jpg',
    englishName: 'Daniella Gilboa',
  },
  {
    name: 'רוני קריבוי',
    age: '25',
    address: ' כרמיאל',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/ql3hysd3/רוני-קריבוי-פייסבוק.png',
    englishName: 'Roni Krivoi',
  },
  {
    name: 'עדינה משה',
    englishName: 'Moshe Adina',
    age: '72',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/5s0fhvml/eyal-nouri.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573763/',
  },
  {
    name: 'גיא גלבוע דלאל',
    age: '22',
    address: ' כפר סבא',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/klbbedaj/גיא-גלבוע-דלאל.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599462/',
    englishName: 'Guy Gilboa Dalal',
  },
  {
    name: 'צחי עידן',
    age: '49',
    address: ' נחל עוז',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/wnjjb4hr/צחי-עידן-פייסבוק.jpg',
    englishName: 'Tsachi Idan',
  },
  {
    name: 'אילנה גריצבסקי',
    age: '30',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/mdofvb3g/אילנה-גריצבסקי-פייסבוק.png',
    englishName: 'Ilana Gritzewsky',
  },
  {
    name: 'עודד ליפשיץ',
    age: '83',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/23fdh13r/עודד-ליפשיץ-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/local/580269/',
    englishName: 'Oded Lipshitz',
  },
  {
    name: 'רז בן עמי',
    age: '57',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/435hgk32/רז-בן-עמי.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599516/',
    englishName: 'Raz Ben Ami',
  },
  {
    name: 'מורן ינאי',
    age: '40',
    address: ' באר שבע',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/mq3ntych/מורן-ינאי.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599427/',
    englishName: 'Moran Yanai',
  },
  {
    name: 'כרמל גת',
    age: '39',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/saufx1dc/כרמל-גת-פייסבוק.jpg',
    englishName: 'Carmel Gat',
  },
  {
    name: 'שושן הרן',
    age: '67',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/swpiw402/שושן-הרן-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/local/574933/',
    englishName: 'Shoshana Haran',
  },
  {
    name: 'גדי משה מוזס',
    age: '79',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/5i3piivv/gadi.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
    englishName: 'Gadi Moshe Mozes',
  },
  {
    name: 'סהר קלדרון',
    age: '16',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/brfd5m1l/סהר-קלדרון.jpg',
    link: 'https://www.kan.org.il/content/kan-news/local/585082/',
    englishName: 'Sahar Kalderon',
  },
  {
    name: 'ארז קלדרון',
    age: '12',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ex2bmz0l/ארז-קלדרון-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan-news/local/583488/',
    englishName: 'Erez Kalderon',
  },
  {
    name: 'עופר קלדרון',
    age: '50',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/o4fhoryx/עופר-קלדרון-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan-news/local/585082/',
    englishName: 'Ofer Kalderon',
  },
  {
    name: 'נעמה לוי',
    age: '19',
    address: ' רעננה',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/d0vfsncw/נעמה-לוי-פייסבוק.jpg',
    englishName: 'Naama Levy',
  },
  {
    name: 'תמר מצגר',
    age: '78',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/jhjai4vn/תמר-מצגר.png',
    link: 'https://www.kan.org.il/content/kan/podcasts/p-579653/191023/587974/',
    englishName: 'Tamar Metzger',
  },
  {
    name: 'יורם מצגר',
    age: '80',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/n3rg2fgi/יורם-מצגר.png',
    link: 'https://www.kan.org.il/content/kan/podcasts/p-579653/191023/587974/',
    englishName: 'Yoram Metzger',
  },
  {
    name: "אלמוג מאיר ג'אן",
    englishName: 'Almog Meir Jan',
    age: '21',
    address: ' אור יהודה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/50bnkspr/אלמוג-מאיר-גאן-פייסבוק.png',
  },
  {
    name: 'אלון אהל',
    age: '22',
    address: ' לבון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/pzmjy5jv/אלון-אהל-פייסבוק.png',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599473/',
    englishName: 'Alon Ohel',
  },
  {
    name: 'עומר שם טוב',
    age: '21',
    address: ' הרצליה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/sa1h5hgt/עומר-שם-טוב.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573754/',
    englishName: 'Omer Shem Tov',
  },
  {
    name: 'עמרי מירן',
    age: '46',
    address: ' נחל עוז',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/d0wbzmfm/עותק-של-lishay_lavi.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573758/',
    englishName: 'Omri Miran',
  },
  {
    name: 'יולי קוניו',
    age: '3',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/h4oipf4t/אמה-קוניו-יולי-קוניו-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
    englishName: 'Yuli Cunio',
  },
  {
    name: 'אמה קוניו',
    age: '3',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/h4oipf4t/אמה-קוניו-יולי-קוניו-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
    englishName: 'Ema Cunio',
  },
  {
    name: 'דוד קוניו',
    age: '33',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/3wbdqmdm/דוד-קוניו.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
    englishName: 'David Cunio',
  },
  {
    name: 'שרון אלוני קוניו',
    age: '34',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/a0xp5mvp/שרון-אלוני-קוניו.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
    englishName: 'Sharon Aloni Cunio',
  },
  {
    name: 'קרינה ארייב',
    age: '19',
    address: ' ירושלים',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/u3flmqmg/קרינה-ארייב.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/575129/',
    englishName: 'Karina Ariev',
  },
  {
    name: 'איתי רגב',
    age: '18',
    address: ' הרצליה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/3s0l5sdc/איתי-רגב.jpg',
    englishName: 'Itay Regev',
  },
  {
    name: 'מיה רגב',
    age: '21',
    address: ' הרצליה',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/5hcpvoxb/מיה-רגב.jpg',
    englishName: 'Maya Regev',
  },
  {
    name: 'אביתר דוד',
    age: '23',
    address: ' כפר סבא',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/5c3fotvc/אביתר-דוד-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573745/',
    englishName: 'Evyatar David',
  },
  {
    name: 'אלה אליקים',
    age: '8',
    address: ' נחל עוז',
    tag: 'נחטפה מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/w03j4aa4/אלה-אליקים-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573748/',
    englishName: 'Ella Elyakim',
  },
  {
    name: 'דפנה אליקים',
    age: '15',
    address: ' נחל עוז',
    tag: 'אלה אליקים',
    img: 'https://cfcdn.kan.org.il/media/fstng4tp/דפנה-אליקים-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573748/',
    englishName: 'Dafna Elyakim',
  },
  {
    name: 'דיצה הימן',
    age: '84',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/o3wnpk1b/דיצה-הימן.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/575122/',
    englishName: 'Ditza Heiman',
  },
  {
    name: 'אמיליה אלוני',
    age: '6',
    address: ' יבנה',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/4hlc1fuq/אמיליה-אלוני.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
    englishName: 'Emilia Aloni',
  },
  {
    name: 'דניאל אלוני',
    age: '45',
    address: ' יבנה',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/0dkhrv4r/דניאל-אלוני-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
    englishName: 'Daniel Aloni',
  },
  {
    name: 'אופיר אנגל',
    age: '17',
    address: ' רמת רחל',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/55ldgatc/אופיר-אנגל-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599531/',
    englishName: 'Ofir Engel',
  },
  {
    name: 'רון שרמן',
    age: '19',
    address: ' להבים',
    tag: 'נחטף מהבסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/wy3jdkqy/רון-שרמן-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599433/',
    englishName: 'Ron Shermann',
  },
  {
    name: 'אוהד מונדר זכרי',
    age: '9',
    address: ' כפר סבא',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/sv0nv5aa/אוהד-מונדר.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
    englishName: 'Ohad Munder Zachri',
  },
  {
    name: 'קרן מונדר',
    age: '54',
    address: ' כפר סבא',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/qksjzge3/קרן-מונדר-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
    englishName: 'Keren Munder',
  },
  {
    name: 'רותי מונדר',
    age: '78',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/el0bcjtb/רותי-מונדר-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
    englishName: 'Ruthi Munder',
  },
  {
    name: 'אברהם מונדר',
    age: '78',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/epwbr2yu/אברהם-מונדר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
    englishName: 'Avraham Munder',
  },
  {
    name: 'איתן יהלומי',
    age: '12',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hbxmopoz/איתן-יהלומי-פייסבוק.jpg',
    englishName: 'Eitan Yahalomi',
  },
  {
    name: 'אוהד יהלומי',
    age: '49',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hdgpf5b1/אוהד-יהלומי-פייסבוק.png',
    englishName: 'Ohad Yahalomi',
  },
  {
    name: 'אוהד בן עמי',
    age: '55',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/o03lbwnv/אוהד-בן-עמי-פייסבוק.png',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599516/',
    englishName: 'Ohad Ben Ami',
  },
  {
    name: 'אגם ברגר',
    age: '20',
    address: ' חולון',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/stcnj1h5/אגם-ברבר-פייסבוק.jpg',
    englishName: 'Agam Berger',
  },
  {
    name: "קית' שמואל סגל",
    age: '64',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/ljgpdu3f/קית-שמואל-סגל-פייסבוק.png',
    englishName: 'Keith Samuel Seagull',
  },
  {
    name: 'אדריאן אביבה סגל',
    age: '62',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/fvnaggn2/אביבה-סגל-פייסבוק.png',
    englishName: 'Adrienne (Aviva) Seagull',
  },
  {
    name: 'עפרי ברודץ',
    age: '10',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/zhmg3x4f/עפרי-ברודץ-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
    englishName: 'Ofry Brodutch',
  },
  {
    name: 'אוריה ברודץ',
    age: '4',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/z32btey2/אוריה-ברודץ-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
    englishName: 'Oria Brodutch',
  },
  {
    name: 'יובל ברודץ',
    age: '8',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/qfwdszd5/יובל-ברודץ-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
    englishName: 'Yuval Brodutch',
  },
  {
    name: 'הגר ברודץ',
    age: '39',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/enzfkvur/הגר-ברודץ.jpg',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
    englishName: 'Hagar Brodutch',
  },
  {
    name: 'יאיר יעקב',
    age: '59',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/lrzexerv/yair.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568687/',
    englishName: 'Yair Yaakov',
  },
  {
    name: 'מירב טל',
    age: '53',
    address: ' ראשון לציון',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/44ifrr3o/מירב-טל-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/589205/',
    englishName: 'Merav Tal',
  },
  {
    name: 'אור לוי',
    age: '33',
    address: ' גבעתיים',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/1elhpajx/אור-לוי-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599495/',
    englishName: 'Or Levi',
  },
  {
    name: 'אליה כהן',
    age: '26',
    address: ' צור הדסה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/cxcli1sl/sigicohen.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573755/',
    englishName: 'Eliya Cohen',
  },
  {
    name: 'אבינתן אור',
    age: '30',
    address: ' תל אביב',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/k3lieyfd/אבינתן-אור.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599518/',
    englishName: 'Avinathan Or',
  },
  {
    name: 'נועה ארגמני',
    age: '26',
    address: ' באר שבע',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/rs0bky4a/נועה-ארגמני.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573751/',
    englishName: 'Noa Argamani',
  },
  {
    name: 'יוסי שרעבי',
    age: '53',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/jjupebsa/יוסי-שרעבי-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599526/',
    englishName: 'Yossi Sharabi',
  },
  {
    name: 'כפיר ביבס',
    age: '9 חודשים',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/exzjde0a/כפיר-ביבס-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/572854/',
    englishName: 'Kfir Bibas',
  },
  {
    name: 'אריאל ביבס',
    age: '4',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/minpipqz/אריאל-ביבס-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/572854/',
    englishName: 'Ariel Bibas',
  },
  {
    name: 'שירי ביבס',
    age: '32',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/isunzplk/שירי-ביבס-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/572854/',
    englishName: 'Shiri Bibas',
  },
  {
    name: 'אלמה אברהם',
    age: '84',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ytchfvi1/אלמה-אברהם-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/573756/',
    englishName: 'Elma Avraham',
  },
  {
    name: 'לירי אלבג',
    age: '18',
    address: ' ירחיב',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/teifnkfv/לירי-אלבג-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599406/',
    englishName: 'Liri Albeg',
  },
  {
    name: 'בר קופרשטיין',
    age: '22',
    address: ' חולון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/u0rkyadc/בר-קופרשטיין-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599528/',
    englishName: 'Bar Kupershtein',
  },
  {
    name: 'מייה שם',
    age: '21',
    address: ' שוהם',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/znnlzfgn/מייה-שם-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599519/',
    englishName: 'Maya Shem',
  },
  {
    name: 'אביב כץ אשר',
    age: '2',
    address: ' גנות הדר',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/50tje5h2/אביב-כץ-אשר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
    englishName: 'Aviv Katz Asher',
  },
  {
    name: 'רז כץ אשר',
    age: '4',
    address: ' גנות הדר',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/nsmgyabk/רז-כץ-אשר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
    englishName: 'Raz Katz Asher',
  },
  {
    name: 'דורון כץ אשר',
    age: '34',
    address: ' גנות הדר',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/gyfdafx4/דורון-כץ-אשר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
    englishName: 'Doron Katz Asher',
  },
  {
    name: 'מייה ליימברג',
    englishName: 'Leimberg Mia',
    age: '17',
    address: ' ירושלים',
    tag: 'נחטפה מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/z4wlmsmj/מייה-ליימברג-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'גבריאלה ליימברג',
    englishName: 'Gabriela Mia',
    age: '59',
    address: ' ירושלים',
    tag: 'נחטפה מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/pegm0k2q/גבריאלה-ליימברג-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'פרננדו מרמן',
    englishName: 'Marman Fernando Simon',
    age: '60',
    address: ' כפר סבא',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/eddfula3/פרננדו-מרמן.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'קלרה מרמן',
    englishName: 'Marman Clara Rosa',
    age: '63',
    address: ' ניר יצחק',
    tag: 'נחטפה מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/qdafpcx1/קלרה-מרמן-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'עומר ונקרט',
    englishName: 'Wenkert Omer',
    age: '22',
    address: ' גדרה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/seeovmba/עומר-ונקרט-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599355/',
  },
  {
    name: 'אלעד קציר',
    englishName: 'Katzir Elad',
    age: '47',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/cr1hoaob/אלעד-קציר.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599525/',
  },
  {
    name: 'אביגיל עידן',
    englishName: 'Abigail Mor Idan',
    age: '3',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/qsudzpkz/אביגיל-עידן-פייסבוק.jpg',
    link: 'https://twitter.com/kann_news/status/1715640878230897066',
  },
  {
    name: 'יפה אדר',
    englishName: 'Adar Yafa',
    age: '85',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ctkhujhs/יפה-אדר.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573752/',
  },
  {
    name: 'ענבר הימן',
    englishName: 'Haiman Inbar',
    age: '27',
    address: ' חיפה',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/nnkcyc1t/ענבר-הימן-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573746/',
  },
];

console.log(hostages.length);

export const englishNames = [
  'Adar Tamir',
  'Adar Yafa',
  'Ahimas Tomer',
  'Albag Liri',
  'Alexander Edan',
  'Aloni Daniel',
  'Aloni Emilia',
  'Al-Sayed Hisham Shaaban',
  'Angrest Matan',
  'Argamani Noa',
  'Ariev Karina',
  'Atzili Aviv',
  'Avigdori Noam',
  'Avigdori Sharon',
  'Avraham Elma',
  'Babadilla Agojo Noralin',
  'Baruch Sahar',
  'Baruch Uriel',
  'Beinin Atzili Liat',
  'Beizer Nik',
  'Ben Ami Ohad',
  'Ben Ami Raz',
  'Benjamin Ron',
  'Berger Agam',
  'Berman Gali',
  'Berman Ziv',
  'Bibas Ariel',
  'Bibas Kfir',
  'Bibas Shiri',
  'Bibas Yarden',
  'Bohbot Elkana',
  'Braslavski Rom',
  'Brodutch Hagar',
  'Brodutch Ofry',
  'Brodutch Oria',
  'Brodutch Yuval',
  'Buchshtab Yagev',
  'Buskila Esther Amit',
  'Chaimi Tal',
  'Chen Itai',
  'Cohen Eliya',
  'Cohen Nimrod',
  'Cohen Sapir',
  'Cooper Amiram',
  'Cunio Ariel',
  'Cunio David',
  'Cunio Ema',
  'Cunio Sharon Aloni',
  'Cunio Yuly',
  'Dancyg Alexander',
  'Danino Ori',
  'David Evyatar',
  'Dekel Chen Sagui',
  'Elgarat Itzhk',
  'Elyakim Dafna',
  'Elyakim Ela',
  'Engel Mika',
  'Engel Ofir',
  'Engel Ronen',
  'Engel Yuval',
  'Engelbert Karina',
  'Gabay Shani',
  'Gat Carmel',
  'Gelerenter Itzhak',
  'Gilboa Daniel',
  'Gilboa-Dalal Guy',
  'Goldin Hadar',
  'Goldstein - Almog Agam',
  'Goldstein - Almog Chen',
  'Goldstein - Almog Gal',
  'Goldstein - Almog Tal',
  'Gonen Romi',
  'Goren Maya',
  'Goren Shani',
  'Gritzewsky Ilana',
  'Gvili Ran',
  'Haggai Gad',
  'Haim Yotam',
  'Haiman Inbar',
  'Har Luis',
  'Heiman Ditza',
  'Herkin Maxim',
  'Hernandez Oryon',
  'Hersh Goldberg Polin',
  'Horn Eitan',
  'Horn Iair',
  'Idan Tsachi',
  'Illouz Guy',
  'Jacob Or',
  'Jacob Yagil',
  'Kalderon Erez',
  'Kalderon Erez',
  'Kalderon Ofer',
  'Kalderon Sahar',
  'Kalderon Sahar',
  'Kalfon Segev',
  'Kaplun Dror',
  'Katz Asher Aviv',
  'Katz Asher Raz',
  'Katz Doron',
  'Katz Ravid',
  'Katzir Elad',
  'Katzir Hanna',
  'Keidar Ofra',
  'Kimenfeld Denil',
  'Kirsht Rimon',
  'Korenberg Hand Emily Tony',
  'Kozlov Andrey',
  'Krivoi Roni',
  'Kupershtein Bar',
  'Leimberg Mia',
  'Leinmberg Gabriela',
  'Levy Eitan',
  'Levy Naama',
  'Levy Or',
  'Libman Elyakim',
  'Lifshitz Oded',
  'Lobanov Alexander',
  'Mansour Shlomo',
  'Margalit Nili',
  'Margalit Nili',
  'Marman Clara Rosa',
  'Marman Clara Rosa',
  'Marman Fernando Simon',
  'Marman Fernando Simon',
  'Meir Jan Almog',
  'Meir Jan Almog',
  'Mengistu Avera',
  'Metzger Tamar',
  'Metzger Yoram',
  'Miran Omri',
  'Mollel Joshua Loitu',
  'Mor Eitan Abraham',
  'Moshe Adina',
  'Mozes Gadi Moshe',
  'Mozes Margalit Berta',
  'Munder Abraham',
  'Munder Keren',
  'Munder Ruth',
  'Munder zachri  Ohad',
  'Munder Zachri Ohad',
  'Neutra Omer',
  'Nimrod Tamir',
  'Nisenbaum Michel',
  'Ohana Yosef',
  'Ohel Alon',
  'Or Alma',
  'Or Avinathan',
  'Or Dror',
  'Or Liam',
  'Or Noam',
  'Pacheco Gelienor',
  'Peri Chaim',
  'Peri Channa',
  'Popplewell Nadav',
  'Regev Itay',
  'Regev Maya',
  'Roitman Ofelia',
  'Roman Gat Yarden',
  'Rotem - Shoshani Hila',
  'Rotem Raaya',
  'Rudaeff Lior',
  'Sagi Ada',
  'Samerano Yonathan Mordechai',
  'Samerano yonathan Mordechai',
  'Sarusi Almog',
  'Schem Mia',
  'Scherman Ron',
  'Shamriz Alon Lulu',
  'Shani Amit',
  'Shani Amit',
  'Sharabi Eli',
  'Sharabi Yossi',
  'Shaul Oron',
  'Shem Tov Omer',
  'Shoham Adi',
  'Shoham Gani  Yahel',
  'Shoham Gani Yahel',
  'Shoham Nave',
  'Shoham Tal',
  'Shoshan Haran',
  'Shtivi Idan',
  'Siegel Adrienne (Aviva)',
  'Siegel Adrienne (Aviva)',
  'Siegel Samuel Keith',
  'Soussana Amit',
  'Steinbrecher Doron',
  'Svirsky Itai',
  'Tal Merav',
  'Tarshansky Gali',
  'Tati Irena',
  'Toledano Elia',
  'Trupanob Alexander (Sasha)',
  'Trupanob Yelena',
  'Tzarfati Ofir',
  'Weinstein Judy',
  'Weiss Ilan',
  'Weiss Noga',
  'Weiss Shiri',
  'Wenkert Omer',
  'Yablonka Chanan',
  'Yahalomi Eitan',
  'Yahalomi Ohad',
  'Yair Yaakov',
  'Yanai Moran Stela',
  'Yehoud Arbel',
  'Yehoud Dolev',
  'Yerushalmi Eden',
  'Zangauker Matan',
  'Zecharya Eden',
];
